name: Feature Request
description: Suggest an idea for tz-client
title: "ENH: "
labels: [Enhancement, Needs Triage]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Feature Type
      description: Please check what type of feature request you would like to propose.
      options:
        - label: >
            Adding new functionality to tz-client
        - label: >
            Changing existing functionality in tz-client
        - label: >
            Removing existing functionality in tz-client
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: >
        Please describe what problem the feature would solve, e.g. "I wish I could use tz-client to ..."
      placeholder: >
        I wish I could use tz-client to..
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: >
        Please describe how the new feature would be implemented, using pseudocode if relevant.
      placeholder: >
        Describe the feature here...
    validations:
        required: true
