# generated by datamodel-codegen:

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, Field

from tz.client.api.schemas import PydanticBaseModel


class AssetCreate(PydanticBaseModel):
    name: str | None = Field(None, title="Name")
    capacity: float | None = Field(None, title="Capacity")
    operating_status: str | None = Field(None, title="Operating Status")
    operating_status_detail: str | None = Field(None, title="Operating Status Detail")
    latitude: float | None = Field(None, title="Latitude")
    longitude: float | None = Field(None, title="Longitude")
    location_accuracy: str | None = Field(None, title="Location Accuracy")
    start_date: AwareDatetime | None = Field(None, title="Start Date")
    retired_date: AwareDatetime | None = Field(None, title="Retired Date")
    planned_retire_date: AwareDatetime | None = Field(None, title="Planned Retire Date")
    construction_date: AwareDatetime | None = Field(None, title="Construction Date")
    constructed_before: AwareDatetime | None = Field(None, title="Constructed Before")
    constructed_after: AwareDatetime | None = Field(None, title="Constructed After")
    node_id: str | None = Field(None, title="Node Id")
    edge_id: str | None = Field(None, title="Edge Id")
    technology_id: str | None = Field(None, title="Technology Id")
    source_scenario_id: str | None = Field(None, title="Source Scenario Id")
    node: dict[str, Any] | None = Field(None, title="node")
    edge: dict[str, Any] | None = Field(None, title="edge")
    technology: str | None = Field(None, title="technology")
    commodities: list[str] | None = Field(None, title="commodities")
    power_unit: dict[str, Any] | None = Field(None, title="power_unit")
    power_plant: dict[str, Any] | None = Field(None, title="power_plant")
    power_transmission: dict[str, Any] | None = Field(None, title="power_transmission")
    sources: list[str] | None = Field(None, title="sources")
    source_scenario: str | None = Field(None, title="source_scenario")


class BodyBulkCreateRunResultsCapacity(PydanticBaseModel):
    file: bytes = Field(..., title="File")


class BodyRecordBulkCreateResource(PydanticBaseModel):
    file: bytes = Field(..., title="File")


class BodyRunResultsChartBulkCreateResource(PydanticBaseModel):
    file: bytes = Field(..., title="File")


class BodyRunResultsCostBulkCreateResource(PydanticBaseModel):
    file: bytes = Field(..., title="File")


class BodyRunResultsExtremaBulkCreateResource(PydanticBaseModel):
    file: bytes = Field(..., title="File")


class BodyRunResultsFlowBulkCreateResource(PydanticBaseModel):
    file: bytes = Field(..., title="File")


class BodyRunResultsMetricBulkCreateResource(PydanticBaseModel):
    file: bytes = Field(..., title="File")


class BodyRunResultsProductionBulkCreateResource(PydanticBaseModel):
    file: bytes = Field(..., title="File")


class CapacityType(Enum):
    gross = "gross"
    new = "new"
    residual = "residual"
    retirement = "retirement"


class CommodityCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    name: str | None = Field(None, title="Name")
    rank: int | None = Field(None, title="Rank")
    properties: dict[str, Any] | None = Field(None, title="Properties")
    technology: str | None = Field(None, title="technology")
    charts: list[str] | None = Field(None, title="charts")
    parents: list[str] | None = Field(None, title="parents")
    children: list[str] | None = Field(None, title="children")


class CommodityResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    name: str | None = Field(None, title="Name")
    rank: int | None = Field(None, title="Rank")
    properties: dict[str, Any] | None = Field(None, title="Properties")
    technology_id: str | None = Field(None, title="Technology Id")
    owner: str | None = Field(None, title="owner")
    technology: str | None = Field(None, title="technology")
    records: list[str] | None = Field(None, title="records")
    charts: list[str] | None = Field(None, title="charts")
    parents: list[str] | None = Field(None, title="parents")
    children: list[str] | None = Field(None, title="children")


class DayPart(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    n_day_parts: int = Field(..., title="N Day Parts")
    order_idx: int = Field(..., title="Order Idx")
    description: str | None = Field(None, title="Description")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str | None = Field(None, title="Owner")
    parent: DayPart | str | None = Field(None, title="Parent")
    children: list[DayPart] | list[str] | None = Field(None, title="Children")


class DayPartCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    n_day_parts: int | None = Field(None, title="N Day Parts")
    order_idx: int | None = Field(None, title="Order Idx")
    description: str | None = Field(None, title="Description")
    parents: list[str] | None = Field(None, title="parents")
    children: list[str] | None = Field(None, title="children")
    records: list[str] | None = Field(None, title="records")


class DayPartPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    day_parts: list[DayPart] | None = Field(..., title="")


class DayPartResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    n_day_parts: int | None = Field(None, title="N Day Parts")
    order_idx: int | None = Field(None, title="Order Idx")
    description: str | None = Field(None, title="Description")
    owner: str | None = Field(None, title="owner")
    parents: list[str] | None = Field(None, title="parents")
    children: list[str] | None = Field(None, title="children")
    records: list[str] | None = Field(None, title="records")


class DeleteResponse(PydanticBaseModel):
    objects_deleted: int = Field(..., title="Objects Deleted")
    message: str | None = Field(None, title="Message")


class EdgeCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    source_node: str | None = Field(None, title="Source Node")
    target_node: str | None = Field(None, title="Target Node")
    is_asset: bool | None = Field(False, title="Is Asset")
    bidirectional: bool | None = Field(True, title="Bidirectional")
    charts: list[str] | None = Field(None, title="charts")
    sources: list[str] | None = Field(None, title="sources")


class EdgeResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    source_node: str | None = Field(None, title="Source Node")
    target_node: str | None = Field(None, title="Target Node")
    is_asset: bool | None = Field(None, title="Is Asset")
    bidirectional: bool | None = Field(None, title="Bidirectional")
    owner: str | None = Field(None, title="owner")
    records: list[str] | None = Field(None, title="records")
    charts: list[str] | None = Field(None, title="charts")
    asset_properties: str | None = Field(None, title="asset_properties")
    sources: list[str] | None = Field(None, title="sources")


class JobCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    status: str | None = Field(None, title="Status")
    successful: bool | None = Field(None, title="Successful")
    run: str | None = Field(None, title="run")


class JobResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    status: str | None = Field(None, title="Status")
    successful: bool | None = Field(None, title="Successful")
    run_id: str | None = Field(None, title="Run Id")
    owner: str | None = Field(None, title="owner")
    run: str | None = Field(None, title="run")


class LicenseCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    name: str | None = Field(None, title="Name")
    abbreviation: str | None = Field(None, title="Abbreviation")
    full_text: str | None = Field(None, title="Full Text")


class LicenseResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    name: str | None = Field(None, title="Name")
    abbreviation: str | None = Field(None, title="Abbreviation")
    full_text: str | None = Field(None, title="Full Text")
    owner: str | None = Field(None, title="owner")
    sources: list[str] | None = Field(None, title="sources")


class ModelCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    name: str | None = Field(None, title="Name")
    description: str | None = Field(None, title="Description")
    version: str | None = Field(None, title="Version")
    start_year: int | None = Field(None, title="Start Year")
    end_year: int | None = Field(None, title="End Year")
    n_year_parts: int | None = Field(1, title="N Year Parts")
    n_day_parts: int | None = Field(1, title="N Day Parts")
    status: str | None = Field("draft", title="Status")
    anon_views: int | None = Field(0, title="Anon Views")
    runs: list[str] | None = Field(None, title="runs")
    featured_scenario: str | None = Field(None, title="featured_scenario")
    commodities: list[str] | None = Field(None, title="commodities")
    edges: list[str] | None = Field(None, title="edges")
    nodes: list[str] | None = Field(None, title="nodes")
    technologies: list[str] | None = Field(None, title="technologies")
    urls: list[str] | None = Field(None, title="urls")
    viewing_users: list[str] | None = Field(None, title="viewing_users")
    starring_users: list[str] | None = Field(None, title="starring_users")


class ModelResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    name: str | None = Field(None, title="Name")
    description: str | None = Field(None, title="Description")
    version: str | None = Field(None, title="Version")
    start_year: int | None = Field(None, title="Start Year")
    end_year: int | None = Field(None, title="End Year")
    n_year_parts: int | None = Field(None, title="N Year Parts")
    n_day_parts: int | None = Field(None, title="N Day Parts")
    status: str | None = Field(None, title="Status")
    anon_views: int | None = Field(None, title="Anon Views")
    owner: str | None = Field(None, title="owner")
    model_scenarios: list[str] | None = Field(None, title="model_scenarios")
    runs: list[str] | None = Field(None, title="runs")
    featured_scenario: str | None = Field(None, title="featured_scenario")
    commodities: list[str] | None = Field(None, title="commodities")
    edges: list[str] | None = Field(None, title="edges")
    nodes: list[str] | None = Field(None, title="nodes")
    technologies: list[str] | None = Field(None, title="technologies")
    urls: list[str] | None = Field(None, title="urls")
    viewing_users: list[str] | None = Field(None, title="viewing_users")
    starring_users: list[str] | None = Field(None, title="starring_users")


class ModelScenarioCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    name: str | None = Field(None, title="Name")
    description: str | None = Field(None, title="Description")
    version: str | None = Field(None, title="Version")
    status: str | None = Field("draft", title="Status")
    featured: bool | None = Field(False, title="Featured")
    model: str | None = Field(None, title="model")
    scenario_heritage: str | None = Field(None, title="scenario_heritage")
    featured_run: str | None = Field(None, title="featured_run")
    urls: list[str] | None = Field(None, title="urls")


class ModelScenarioResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    name: str | None = Field(None, title="Name")
    description: str | None = Field(None, title="Description")
    version: str | None = Field(None, title="Version")
    status: str | None = Field(None, title="Status")
    featured: bool | None = Field(None, title="Featured")
    model_id: str | None = Field(None, title="Model Id")
    scenario_index_id: str | None = Field(None, title="Scenario Index Id")
    scenario_heritage_id: str | None = Field(None, title="Scenario Heritage Id")
    owner: str | None = Field(None, title="owner")
    model: str | None = Field(None, title="model")
    scenario_index: str | None = Field(None, title="scenario_index")
    scenario_heritage: str | None = Field(None, title="scenario_heritage")
    featured_run: str | None = Field(None, title="featured_run")
    runs: list[str] | None = Field(None, title="runs")
    records: list[str] | None = Field(None, title="records")
    urls: list[str] | None = Field(None, title="urls")


class NodeAliasCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    alias_type: str | None = Field(None, title="Alias Type")
    alias_lang: str | None = Field(None, title="Alias Lang")
    primary: bool | None = Field(None, title="Primary")
    node: str | None = Field(None, title="node")
    power_unit: str | None = Field(None, title="power_unit")


class NodeAliasResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    alias_type: str | None = Field(None, title="Alias Type")
    alias_lang: str | None = Field(None, title="Alias Lang")
    primary: bool | None = Field(None, title="Primary")
    node_id: str | None = Field(None, title="Node Id")
    power_unit_id: str | None = Field(None, title="Power Unit Id")
    owner: str | None = Field(None, title="owner")
    node: str | None = Field(None, title="node")
    power_unit: str | None = Field(None, title="power_unit")


class NodeType(Enum):
    power_unit = "power_unit"
    power_plant = "power_plant"
    admin_1 = "admin_1"
    grid_region = "grid_region"
    admin_0 = "admin_0"
    region_a = "region_a"
    region_b = "region_b"
    continent = "continent"
    root = "root"
    unknown = "unknown"


class NodeTypeAlias(Enum):
    power_unit = "power_unit"
    power_plant = "power_plant"
    power_transmission = "power_transmission"
    grid_region = "grid_region"
    balancing_authority = "balancing_authority"
    country = "country"
    province = "province"
    major_sub_region = "major_sub_region"
    minor_sub_region = "minor_sub_region"
    continent = "continent"
    root = "root"
    unknown = "unknown"
    administrative_area = "administrative_area"
    administrative_subdivisions = "administrative_subdivisions"
    arctic_region = "arctic_region"
    arrondissement = "arrondissement"
    atoll = "atoll"
    autonomous_city = "autonomous_city"
    autonomous_commune = "autonomous_commune"
    autonomous_community = "autonomous_community"
    autonomous_district = "autonomous_district"
    autonomous_island = "autonomous_island"
    autonomous_province = "autonomous_province"
    autonomous_region = "autonomous_region"
    autonomous_republic = "autonomous_republic"
    autonomous_sector = "autonomous_sector"
    autonomous_territory = "autonomous_territory"
    borough = "borough"
    canton = "canton"
    capital_city = "capital_city"
    capital_district = "capital_district"
    capital_metropolitan_city = "capital_metropolitan_city"
    capital_territory = "capital_territory"
    captial_city_district = "captial_city_district"
    centrally_administered_area = "centrally_administered_area"
    circuit = "circuit"
    city = "city"
    commissiary = "commissiary"
    commune = "commune"
    constituent_country = "constituent_country"
    county = "county"
    decentralized_administration = "decentralized_administration"
    department = "department"
    dependency = "dependency"
    development_region = "development_region"
    directly_governed_city = "directly_governed_city"
    district = "district"
    districts_of_republican_subordin = "districts_of_republican_subordin"
    division = "division"
    economic_prefecture = "economic_prefecture"
    emirate = "emirate"
    entity = "entity"
    federal_district = "federal_district"
    federal_territory = "federal_territory"
    free_state = "free_state"
    governorate = "governorate"
    group_of_islands = "group_of_islands"
    independent_city = "independent_city"
    independent_town = "independent_town"
    indigenous_territory = "indigenous_territory"
    intendancy = "intendancy"
    island = "island"
    island_council = "island_council"
    island_group = "island_group"
    kingdom = "kingdom"
    metropolian_region = "metropolian_region"
    metropolis = "metropolis"
    metropolitan_autonomous_city = "metropolitan_autonomous_city"
    metropolitan_city = "metropolitan_city"
    municipality = "municipality"
    municipality_prefecture = "municipality_prefecture"
    national_district = "national_district"
    national_park = "national_park"
    outer_islands = "outer_islands"
    outlying_area = "outlying_area"
    overseas_collectivity = "overseas_collectivity"
    overseas_territory = "overseas_territory"
    parish = "parish"
    parish_district = "parish_district"
    prefecture = "prefecture"
    quarter = "quarter"
    reef = "reef"
    region = "region"
    republic = "republic"
    sovereign_base_area = "sovereign_base_area"
    special_administrative_region = "special_administrative_region"
    special_city = "special_city"
    special_municipality = "special_municipality"
    special_region_zone = "special_region_zone"
    state = "state"
    statistical_region = "statistical_region"
    sub_region = "sub_region"
    territorial_unit = "territorial_unit"
    territory = "territory"
    town = "town"
    town_council = "town_council"
    town_district = "town_district"
    unincorporated_territory = "unincorporated_territory"
    union_territory = "union_territory"
    urban_prefecture = "urban_prefecture"
    village_district = "village_district"
    voivodeship = "voivodeship"


class NodesOrEdgesType(Enum):
    nodes = "nodes"
    edges = "edges"


class OperatingModeCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    name: str | None = Field(None, title="Name")
    properties: dict[str, Any] | None = Field(None, title="Properties")
    technology: str | None = Field(None, title="technology")


class OperatingModeResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    name: str | None = Field(None, title="Name")
    properties: dict[str, Any] | None = Field(None, title="Properties")
    technology_id: str | None = Field(None, title="Technology Id")
    owner: str | None = Field(None, title="owner")
    technology: str | None = Field(None, title="technology")
    records: list[str] | None = Field(None, title="records")


class ParameterCreateSchema(PydanticBaseModel):
    record_type: str = Field(..., title="Record Type")
    node: str | None = Field(None, title="Node")
    edge: str | None = Field(None, title="Edge")
    technology: str = Field(..., title="Technology")
    commodity: str = Field(..., title="Commodity")
    operating_mode: str = Field(..., title="Operating Mode")
    year: int = Field(..., title="Year")
    year_part: str = Field(..., title="Year Part")
    day_part: str = Field(..., title="Day Part")
    value: float = Field(..., title="Value")
    model_scenario: str | None = Field(None, title="Model Scenario")


class ParameterPostResponseSchema(PydanticBaseModel):
    created: list[UUID] = Field(..., title="Created")
    updated: list[UUID] = Field(..., title="Updated")


class ParameterPostSchema(PydanticBaseModel):
    parameters: list[ParameterCreateSchema] = Field(..., title="Parameters")


class PowerPlant(PydanticBaseModel):
    asset_id: UUID = Field(..., title="Asset Id")


class PowerTransmission(PydanticBaseModel):
    asset_id: UUID = Field(..., title="Asset Id")
    capacity_reverse: float | None = Field(None, title="Capacity Reverse")
    voltage: float | None = Field(None, title="Voltage")
    segments: dict[str, Any] | None = Field(None, title="Segments")


class PublisherCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    name: str | None = Field(None, title="Name")
    organisation_type: str | None = Field(None, title="Organisation Type")
    short_name: str | None = Field(None, title="Short Name")
    url: str | None = Field(None, title="Url")
    source_scenarios: list[str] | None = Field(None, title="source_scenarios")


class PublisherResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    name: str | None = Field(None, title="Name")
    organisation_type: str | None = Field(None, title="Organisation Type")
    short_name: str | None = Field(None, title="Short Name")
    url: str | None = Field(None, title="Url")
    owner: str | None = Field(None, title="owner")
    sources: list[str] | None = Field(None, title="sources")
    source_scenarios: list[str] | None = Field(None, title="source_scenarios")


class RecordCreate(PydanticBaseModel):
    public: bool | None = Field(True, title="Public")
    year: int | None = Field(None, title="Year")
    timestamp: AwareDatetime | None = Field(None, title="Timestamp")
    value: float | None = Field(None, title="Value")
    properties: dict[str, Any] | None = Field(None, title="Properties")
    year_part_id: str | None = Field(None, title="Year Part Id")
    day_part_id: str | None = Field(None, title="Day Part Id")
    record_type: str | None = Field(None, title="Record Type")
    year_part: str | None = Field(None, title="year_part")
    day_part: str | None = Field(None, title="day_part")
    node: str | None = Field(None, title="node")
    edge: str | None = Field(None, title="edge")
    model_scenario: str | None = Field(None, title="model_scenario")
    source_scenario: str | None = Field(None, title="source_scenario")
    technology: str | None = Field("NA", title="technology")
    commodity: str | None = Field("NA", title="commodity")
    operating_mode: str | None = Field("NA", title="operating_mode")


class RecordResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    year: int | None = Field(None, title="Year")
    timestamp: AwareDatetime | None = Field(None, title="Timestamp")
    value: float | None = Field(None, title="Value")
    properties: dict[str, Any] | None = Field(None, title="Properties")
    year_part_id: str | None = Field(None, title="Year Part Id")
    day_part_id: str | None = Field(None, title="Day Part Id")
    node_id: str | None = Field(None, title="Node Id")
    edge_id: str | None = Field(None, title="Edge Id")
    model_scenario_id: str | None = Field(None, title="Model Scenario Id")
    source_scenario_id: str | None = Field(None, title="Source Scenario Id")
    technology_id: str | None = Field(None, title="Technology Id")
    commodity_id: str | None = Field(None, title="Commodity Id")
    operating_mode_id: str | None = Field(None, title="Operating Mode Id")
    record_type: str | None = Field(None, title="Record Type")
    owner: str | None = Field(None, title="owner")
    year_part: str | None = Field(None, title="year_part")
    day_part: str | None = Field(None, title="day_part")
    node: str | None = Field(None, title="node")
    edge: str | None = Field(None, title="edge")
    model_scenario: str | None = Field(None, title="model_scenario")
    source_scenario: str | None = Field(None, title="source_scenario")
    technology: str | None = Field(None, title="technology")
    commodity: str | None = Field(None, title="commodity")
    operating_mode: str | None = Field(None, title="operating_mode")


class RecordType(PydanticBaseModel):
    slug: str = Field(..., title="Slug")
    units: str = Field(..., title="Units")
    description: str = Field(..., title="Description")
    aggregating_operation: str = Field(..., title="Aggregating Operation")
    scale: int | None = Field(None, title="Scale")


class ResidualCapacityDataPoint(PydanticBaseModel):
    year: int = Field(..., title="Year")
    value: float = Field(..., title="Value")
    unit: str = Field(..., title="Unit")


class ResidualCapacityTimeseries(PydanticBaseModel):
    unit: str = Field(..., title="Unit")
    residual_capacity_timeseries: list[ResidualCapacityDataPoint] = Field(
        ..., title="Residual Capacity Timeseries"
    )
    technology: str = Field(..., title="Technology")
    node: str = Field(..., title="Node")


class RunCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    name: str | None = Field(None, title="Name")
    run_spec: dict[str, Any] | None = Field(None, title="Run Spec")
    validated: bool | None = Field(False, title="Validated")
    description: str | None = Field(None, title="Description")
    featured: bool | None = Field(False, title="Featured")
    model_id: str | None = Field(None, title="Model Id")
    model: str | None = Field(None, title="model")
    model_scenario: str | None = Field(None, title="model_scenario")
    urls: list[str] | None = Field(None, title="urls")
    run_results_capacity: list[str] | None = Field(None, title="run_results_capacity")
    run_results_flow: list[str] | None = Field(None, title="run_results_flow")
    run_results_cost: list[str] | None = Field(None, title="run_results_cost")
    run_results_metric: list[str] | None = Field(None, title="run_results_metric")
    run_results_extrema: list[str] | None = Field(None, title="run_results_extrema")
    run_results_chart: list[str] | None = Field(None, title="run_results_chart")
    run_results_production: list[str] | None = Field(None, title="run_results_production")


class RunResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    name: str | None = Field(None, title="Name")
    run_spec: dict[str, Any] | None = Field(None, title="Run Spec")
    validated: bool | None = Field(None, title="Validated")
    description: str | None = Field(None, title="Description")
    featured: bool | None = Field(None, title="Featured")
    model_id: str | None = Field(None, title="Model Id")
    model_scenario_id: str | None = Field(None, title="Model Scenario Id")
    owner: str | None = Field(None, title="owner")
    model: str | None = Field(None, title="model")
    model_scenario: str | None = Field(None, title="model_scenario")
    jobs: list[str] | None = Field(None, title="jobs")
    urls: list[str] | None = Field(None, title="urls")
    run_results_capacity: list[str] | None = Field(None, title="run_results_capacity")
    run_results_flow: list[str] | None = Field(None, title="run_results_flow")
    run_results_cost: list[str] | None = Field(None, title="run_results_cost")
    run_results_metric: list[str] | None = Field(None, title="run_results_metric")
    run_results_extrema: list[str] | None = Field(None, title="run_results_extrema")
    run_results_chart: list[str] | None = Field(None, title="run_results_chart")
    run_results_production: list[str] | None = Field(None, title="run_results_production")


class RunResultsCapacity(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    year: int = Field(..., title="Year")
    capacity_type: CapacityType
    nodes_or_edges: NodesOrEdgesType
    data: dict[str, Any] = Field(..., title="Data")


class RunResultsCapacityCreate(PydanticBaseModel):
    year: int | None = Field(None, title="Year")
    capacity_type: CapacityType | None = None
    nodes_or_edges: NodesOrEdgesType | None = None
    data: dict[str, Any] | None = Field(None, title="Data")
    run: str | None = Field(None, title="run")


class RunResultsCapacityPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    run_results_capacity: list[RunResultsCapacity] | None = Field(..., title="")


class RunResultsChartCreate(PydanticBaseModel):
    chart_type: str | None = Field(None, title="Chart Type")
    series_name: str | None = Field(None, title="Series Name")
    series_properties: dict[str, Any] | None = Field(None, title="Series Properties")
    year: int | None = Field(None, title="Year")
    x: list[float] | None = Field(None, title="X")
    y: list[float] | None = Field(None, title="Y")
    node_id: str | None = Field(None, title="Node Id")
    edge_id: str | None = Field(None, title="Edge Id")
    technology_id: str | None = Field(None, title="Technology Id")
    commodity_id: str | None = Field(None, title="Commodity Id")
    year_part_id: str | None = Field(None, title="Year Part Id")
    run: str | None = Field(None, title="run")
    node: str | None = Field(None, title="node")
    edge: str | None = Field(None, title="edge")
    technology: str | None = Field(None, title="technology")
    commodity: str | None = Field(None, title="commodity")
    year_part: str | None = Field(None, title="year_part")


class RunResultsCostCreate(PydanticBaseModel):
    year: int | None = Field(None, title="Year")
    data: dict[str, Any] | None = Field(None, title="Data")
    year_part: str | None = Field(None, title="Year Part")
    day_part: str | None = Field(None, title="Day Part")
    run: str | None = Field(None, title="run")


class RunResultsExtremaCreate(PydanticBaseModel):
    datum: str | None = Field(None, title="Datum")
    min_value: float | None = Field(None, title="Min Value")
    min_year: int | None = Field(None, title="Min Year")
    max_value: float | None = Field(None, title="Max Value")
    max_year: int | None = Field(None, title="Max Year")
    min_year_part: str | None = Field(None, title="Min Year Part")
    min_day_part: str | None = Field(None, title="Min Day Part")
    max_year_part: str | None = Field(None, title="Max Year Part")
    max_day_part: str | None = Field(None, title="Max Day Part")
    run: str | None = Field(None, title="run")


class RunResultsFlowCreate(PydanticBaseModel):
    year: int | None = Field(None, title="Year")
    data: dict[str, Any] | None = Field(None, title="Data")
    year_part: str | None = Field(None, title="Year Part")
    day_part: str | None = Field(None, title="Day Part")
    run: str | None = Field(None, title="run")


class RunResultsMetric(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    unit: str = Field(..., title="Unit")
    value: float = Field(..., title="Value")
    metric: str = Field(..., title="Metric")


class RunResultsMetricCreate(PydanticBaseModel):
    unit: str | None = Field(None, title="Unit")
    value: float | None = Field(None, title="Value")
    metric: str | None = Field(None, title="Metric")
    run: str | None = Field(None, title="run")


class RunResultsMetricPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    run_results_metrics: list[RunResultsMetric] | None = Field(..., title="")


class RunResultsProductionCreate(PydanticBaseModel):
    year: int | None = Field(None, title="Year")
    data: dict[str, Any] | None = Field(None, title="Data")
    year_part: str | None = Field(None, title="Year Part")
    day_part: str | None = Field(None, title="Day Part")
    run: str | None = Field(None, title="run")


class ScenarioIndex(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")


class SourceCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    name: str | None = Field(None, title="Name")
    short_name: str | None = Field(None, title="Short Name")
    description: str | None = Field(None, title="Description")
    year: int | None = Field(None, title="Year")
    month: int | None = Field(None, title="Month")
    day: int | None = Field(None, title="Day")
    quarter: int | None = Field(None, title="Quarter")
    url: str | None = Field(None, title="Url")
    publisher: str | None = Field(None, title="publisher")
    license: str | None = Field(None, title="license")


class SourceResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    name: str | None = Field(None, title="Name")
    short_name: str | None = Field(None, title="Short Name")
    description: str | None = Field(None, title="Description")
    year: int | None = Field(None, title="Year")
    month: int | None = Field(None, title="Month")
    day: int | None = Field(None, title="Day")
    quarter: int | None = Field(None, title="Quarter")
    url: str | None = Field(None, title="Url")
    publisher_id: str | None = Field(None, title="Publisher Id")
    license_id: str | None = Field(None, title="License Id")
    owner: str | None = Field(None, title="owner")
    publisher: str | None = Field(None, title="publisher")
    license: str | None = Field(None, title="license")
    nodes: list[str] | None = Field(None, title="nodes")


class SourceScenarioCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    name: str | None = Field(None, title="Name")
    description: str | None = Field(None, title="Description")
    version: str | None = Field(None, title="Version")
    status: str | None = Field("draft", title="Status")
    featured: bool | None = Field(False, title="Featured")
    publisher_id: str | None = Field(None, title="Publisher Id")
    publisher: str | None = Field(None, title="publisher")
    source: str | None = Field(None, title="source")
    records: list[str] | None = Field(None, title="records")
    assets: list[str] | None = Field(None, title="assets")


class SourceScenarioResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    name: str | None = Field(None, title="Name")
    description: str | None = Field(None, title="Description")
    version: str | None = Field(None, title="Version")
    status: str | None = Field(None, title="Status")
    featured: bool | None = Field(None, title="Featured")
    publisher_id: str | None = Field(None, title="Publisher Id")
    source_id: str | None = Field(None, title="Source Id")
    scenario_index_id: str | None = Field(None, title="Scenario Index Id")
    owner: str | None = Field(None, title="owner")
    publisher: str | None = Field(None, title="publisher")
    source: str | None = Field(None, title="source")
    scenario_index: str | None = Field(None, title="scenario_index")
    records: list[str] | None = Field(None, title="records")
    assets: list[str] | None = Field(None, title="assets")


class TechnologyCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    name: str | None = Field(None, title="Name")
    rank: int | None = Field(None, title="Rank")
    is_storage: bool | None = Field(False, title="Is Storage")
    properties: dict[str, Any] | None = Field(None, title="Properties")
    commodities: list[str] | None = Field(None, title="commodities")
    assets: list[str] | None = Field(None, title="assets")
    records: list[str] | None = Field(None, title="records")
    charts: list[str] | None = Field(None, title="charts")
    operating_modes: list[str] | None = Field(None, title="operating_modes")
    parents: list[str] | None = Field(None, title="parents")
    children: list[str] | None = Field(None, title="children")


class TechnologyResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    name: str | None = Field(None, title="Name")
    rank: int | None = Field(None, title="Rank")
    is_storage: bool | None = Field(None, title="Is Storage")
    properties: dict[str, Any] | None = Field(None, title="Properties")
    owner: str | None = Field(None, title="owner")
    commodities: list[str] | None = Field(None, title="commodities")
    assets: list[str] | None = Field(None, title="assets")
    records: list[str] | None = Field(None, title="records")
    charts: list[str] | None = Field(None, title="charts")
    operating_modes: list[str] | None = Field(None, title="operating_modes")
    parents: list[str] | None = Field(None, title="parents")
    children: list[str] | None = Field(None, title="children")


class URLType(Enum):
    docs_github = "docs-github"
    docs_api = "docs-api"
    docs_python = "docs-python"
    insights_internal = "insights-internal"
    insights_external = "insights-external"


class UrlIndexCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    url: str | None = Field(None, title="Url")
    url_type: URLType | None = None
    properties: dict[str, Any] | None = Field(None, title="Properties")
    model: str | None = Field(None, title="model")
    model_scenario: str | None = Field(None, title="model_scenario")
    run: str | None = Field(None, title="run")


class UrlIndexResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    url: str | None = Field(None, title="Url")
    url_type: URLType | None = None
    properties: dict[str, Any] | None = Field(None, title="Properties")
    model_id: str | None = Field(None, title="Model Id")
    model_scenario_id: str | None = Field(None, title="Model Scenario Id")
    run_id: str | None = Field(None, title="Run Id")
    owner: str | None = Field(None, title="owner")
    model: str | None = Field(None, title="model")
    model_scenario: str | None = Field(None, title="model_scenario")
    run: str | None = Field(None, title="run")


class User(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(False, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    role: str = Field(..., title="Role")
    permissions: list[str] | None = Field(None, title="Permissions")
    username: str = Field(..., title="Username")
    email: str | None = Field(None, title="Email")
    tenant: str = Field(..., title="Tenant")
    auth0_creation_time: AwareDatetime | None = Field(None, title="Auth0 Creation Time")
    email_verified: bool | None = Field(False, title="Email Verified")
    family_name: str | None = Field(None, title="Family Name")
    given_name: str | None = Field(None, title="Given Name")
    last_password_reset: AwareDatetime | None = Field(None, title="Last Password Reset")
    phone_number: str | None = Field(None, title="Phone Number")
    phone_verified: bool | None = Field(False, title="Phone Verified")
    picture: str | None = Field(None, title="Picture")
    updated_at: AwareDatetime | None = Field(None, title="Updated At")
    organisation: str | None = Field(None, title="Organisation")
    job_title: str | None = Field(None, title="Job Title")
    contact_consent: bool | None = Field(False, title="Contact Consent")
    terms_conditions_accepted: bool | None = Field(None, title="Terms Conditions Accepted")
    country: str | None = Field(None, title="Country")
    industry_sector: str | None = Field(None, title="Industry Sector")
    owner: User | str | None = Field(..., title="Owner")


class UserCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(False, title="Public")
    role: str | None = Field(None, title="Role")
    permissions: list[str] | None = Field(None, title="Permissions")
    username: str | None = Field(None, title="Username")
    email: str | None = Field(None, title="Email")
    tenant: str | None = Field(None, title="Tenant")
    auth0_creation_time: AwareDatetime | None = Field(None, title="Auth0 Creation Time")
    email_verified: bool | None = Field(False, title="Email Verified")
    family_name: str | None = Field(None, title="Family Name")
    given_name: str | None = Field(None, title="Given Name")
    last_password_reset: AwareDatetime | None = Field(None, title="Last Password Reset")
    phone_number: str | None = Field(None, title="Phone Number")
    phone_verified: bool | None = Field(False, title="Phone Verified")
    picture: str | None = Field(None, title="Picture")
    updated_at: AwareDatetime | None = Field(None, title="Updated At")
    organisation: str | None = Field(None, title="Organisation")
    job_title: str | None = Field(None, title="Job Title")
    contact_consent: bool | None = Field(False, title="Contact Consent")
    terms_conditions_accepted: bool | None = Field(None, title="Terms Conditions Accepted")
    country: str | None = Field(None, title="Country")
    industry_sector: str | None = Field(None, title="Industry Sector")
    app_metadata: dict[str, Any] | None = Field(None, title="App Metadata")
    user_metadata: dict[str, Any] | None = Field(None, title="User Metadata")


class UserPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    users: list[User] | None = Field(..., title="")


class UserResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    role: str | None = Field(None, title="Role")
    permissions: list[str] | None = Field(None, title="Permissions")
    username: str | None = Field(None, title="Username")
    email: str | None = Field(None, title="Email")
    tenant: str | None = Field(None, title="Tenant")
    auth0_creation_time: AwareDatetime | None = Field(None, title="Auth0 Creation Time")
    email_verified: bool | None = Field(None, title="Email Verified")
    family_name: str | None = Field(None, title="Family Name")
    given_name: str | None = Field(None, title="Given Name")
    last_password_reset: AwareDatetime | None = Field(None, title="Last Password Reset")
    phone_number: str | None = Field(None, title="Phone Number")
    phone_verified: bool | None = Field(None, title="Phone Verified")
    picture: str | None = Field(None, title="Picture")
    updated_at: AwareDatetime | None = Field(None, title="Updated At")
    organisation: str | None = Field(None, title="Organisation")
    job_title: str | None = Field(None, title="Job Title")
    contact_consent: bool | None = Field(None, title="Contact Consent")
    terms_conditions_accepted: bool | None = Field(None, title="Terms Conditions Accepted")
    country: str | None = Field(None, title="Country")
    industry_sector: str | None = Field(None, title="Industry Sector")
    app_metadata: dict[str, Any] | None = Field(None, title="App Metadata")
    user_metadata: dict[str, Any] | None = Field(None, title="User Metadata")
    owner: str | None = Field(None, title="owner")


class ValidationError(PydanticBaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class YearPart(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    n_year_parts: int = Field(..., title="N Year Parts")
    order_idx: int = Field(..., title="Order Idx")
    description: str | None = Field(None, title="Description")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str | None = Field(None, title="Owner")
    parent: YearPart | str | None = Field(None, title="Parent")
    children: list[YearPart] | list[str] | None = Field(None, title="Children")


class YearPartCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    n_year_parts: int | None = Field(None, title="N Year Parts")
    order_idx: int | None = Field(None, title="Order Idx")
    description: str | None = Field(None, title="Description")
    parents: list[str] | None = Field(None, title="parents")
    children: list[str] | None = Field(None, title="children")
    records: list[str] | None = Field(None, title="records")
    charts: list[str] | None = Field(None, title="charts")


class YearPartPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    year_parts: list[YearPart] | None = Field(..., title="")


class YearPartResource(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    owner_id: UUID = Field(..., title="Owner Id")
    n_year_parts: int = Field(..., title="N Year Parts")
    order_idx: int = Field(..., title="Order Idx")
    description: str | None = Field(None, title="Description")


class YearPartResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    n_year_parts: int | None = Field(None, title="N Year Parts")
    order_idx: int | None = Field(None, title="Order Idx")
    description: str | None = Field(None, title="Description")
    owner: str | None = Field(None, title="owner")
    parents: list[str] | None = Field(None, title="parents")
    children: list[str] | None = Field(None, title="children")
    records: list[str] | None = Field(None, title="records")
    charts: list[str] | None = Field(None, title="charts")


class HTTPValidationError(PydanticBaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")


class MultiResidualCapacityResponse(PydanticBaseModel):
    model_scenario_slug: str = Field(..., title="Model Scenario Slug")
    model_scenario_residual_capacities: list[ResidualCapacityTimeseries] = Field(
        ..., title="Model Scenario Residual Capacities"
    )


class NodeCreate(PydanticBaseModel):
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    node_type_alias: NodeTypeAlias | None = None
    properties: dict[str, Any] | None = Field(None, title="Properties")
    is_asset: bool | None = Field(False, title="Is Asset")
    charts: list[str] | None = Field(None, title="charts")
    node_type: str | None = Field(None, title="node_type")
    parents: list[str] | None = Field(None, title="parents")
    children: list[str] | None = Field(None, title="children")
    neighbours_out: list[str] | None = Field(None, title="neighbours_out")
    neighbours_in: list[str] | None = Field(None, title="neighbours_in")
    sources: list[str] | None = Field(None, title="sources")


class NodeResourcePatch(PydanticBaseModel):
    uuid: str | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(None, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    owner_id: str | None = Field(None, title="Owner Id")
    node_type_alias: NodeTypeAlias | None = None
    properties: dict[str, Any] | None = Field(None, title="Properties")
    is_asset: bool | None = Field(None, title="Is Asset")
    node_type_discriminator: NodeType | None = None
    owner: str | None = Field(None, title="owner")
    aliases: list[str] | None = Field(None, title="aliases")
    records: list[str] | None = Field(None, title="records")
    charts: list[str] | None = Field(None, title="charts")
    asset_properties: str | None = Field(None, title="asset_properties")
    node_type: str | None = Field(None, title="node_type")
    parents: list[str] | None = Field(None, title="parents")
    children: list[str] | None = Field(None, title="children")
    neighbours_out: list[str] | None = Field(None, title="neighbours_out")
    neighbours_in: list[str] | None = Field(None, title="neighbours_in")
    sources: list[str] | None = Field(None, title="sources")


class RunResultsCost(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    year: int = Field(..., title="Year")
    data: dict[str, Any] = Field(..., title="Data")
    year_part: YearPart | str = Field(..., title="Year Part")
    day_part: DayPart | str = Field(..., title="Day Part")


class RunResultsCostPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    run_results_cost: list[RunResultsCost] | None = Field(..., title="")


class RunResultsExtrema(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    datum: str = Field(..., title="Datum")
    min_value: float = Field(..., title="Min Value")
    min_year: int = Field(..., title="Min Year")
    max_value: float = Field(..., title="Max Value")
    max_year: int = Field(..., title="Max Year")
    min_year_part: YearPart | str = Field(..., title="Min Year Part")
    min_day_part: DayPart | str = Field(..., title="Min Day Part")
    max_year_part: YearPart | str = Field(..., title="Max Year Part")
    max_day_part: DayPart | str = Field(..., title="Max Day Part")


class RunResultsExtremaPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    run_results_extrema: list[RunResultsExtrema] | None = Field(..., title="")


class RunResultsFlow(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    year: int = Field(..., title="Year")
    data: dict[str, Any] = Field(..., title="Data")
    year_part: YearPart | str = Field(..., title="Year Part")
    day_part: DayPart | str = Field(..., title="Day Part")


class RunResultsFlowPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    run_results_flow: list[RunResultsFlow] | None = Field(..., title="")


class RunResultsProduction(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    year: int = Field(..., title="Year")
    data: dict[str, Any] = Field(..., title="Data")
    year_part: YearPart | str = Field(..., title="Year Part")
    day_part: DayPart | str = Field(..., title="Day Part")


class RunResultsProductionPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    run_results_production: list[RunResultsProduction] | None = Field(..., title="")


class Asset(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    name: str | None = Field(None, title="Name")
    public: bool | None = Field(True, title="Public")
    capacity: float | None = Field(None, title="Capacity")
    operating_status: str | None = Field(None, title="Operating Status")
    operating_status_detail: str | None = Field(None, title="Operating Status Detail")
    latitude: float | None = Field(None, title="Latitude")
    longitude: float | None = Field(None, title="Longitude")
    location_accuracy: str | None = Field(None, title="Location Accuracy")
    start_date: AwareDatetime | None = Field(None, title="Start Date")
    retired_date: AwareDatetime | None = Field(None, title="Retired Date")
    planned_retire_date: AwareDatetime | None = Field(None, title="Planned Retire Date")
    construction_date: AwareDatetime | None = Field(None, title="Construction Date")
    constructed_before: AwareDatetime | None = Field(None, title="Constructed Before")
    constructed_after: AwareDatetime | None = Field(None, title="Constructed After")
    edge: Edge | str | None = Field(None, title="Edge")
    node: Node | str | None = Field(None, title="Node")
    technology: str | Technology | None = Field(None, title="Technology")
    commodities: list[str | Commodity] | None = Field(None, title="Commodities")
    parents: list[str] | list[Node] | None = Field(None, title="Parents")
    children: list[str] | list[Node] | None = Field(None, title="Children")
    power_unit: str | PowerUnit | None = Field(None, title="Power Unit")
    power_plant: str | PowerPlant | None = Field(None, title="Power Plant")
    power_transmission: str | PowerTransmission | None = Field(None, title="Power Transmission")
    sources: list[Source] | list[str] | None = Field(None, title="Sources")
    source_scenario: SourceScenario | str | None = Field(None, title="Source Scenario")


class AssetPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    assets: list[Asset] | None = Field(..., title="")


class Commodity(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    name: str = Field(..., title="Name")
    rank: int | None = Field(None, title="Rank")
    properties: dict[str, Any] | None = Field(None, title="Properties")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str = Field(..., title="Owner")
    technology: str | Technology | None = Field(None, title="Technology")
    parents: list[Commodity] | list[str] | None = Field(None, title="Parents")
    children: list[Commodity] | list[str] | None = Field(None, title="Children")


class CommodityPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    commodities: list[Commodity] | None = Field(..., title="")


class Edge(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str = Field(..., title="Owner")
    source_node: Node | str | None = Field(None, title="Source Node")
    target_node: Node | str | None = Field(None, title="Target Node")
    is_asset: bool = Field(..., title="Is Asset")
    sources: list[Source] | list[str] | None = Field(None, title="Sources")


class EdgePagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    edges: list[Edge] | None = Field(..., title="")


class Job(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    status: str = Field(..., title="Status")
    successful: bool | None = Field(None, title="Successful")
    owner: str = Field(..., title="Owner")
    run: str | Run = Field(..., title="Run")


class JobPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    jobs: list[Job] | None = Field(..., title="")


class License(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    name: str = Field(..., title="Name")
    abbreviation: str = Field(..., title="Abbreviation")
    full_text: str = Field(..., title="Full Text")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str = Field(..., title="Owner")
    sources: list[Source] | list[str] | None = Field(None, title="Sources")


class LicensePagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    licenses: list[License] | None = Field(..., title="")


class Model(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    version: str | None = Field(None, title="Version")
    start_year: int = Field(..., title="Start Year")
    end_year: int = Field(..., title="End Year")
    n_year_parts: int | None = Field(1, title="N Year Parts")
    n_day_parts: int | None = Field(1, title="N Day Parts")
    status: str | None = Field("draft", title="Status")
    anon_views: int | None = Field(0, title="Anon Views")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str = Field(..., title="Owner")
    edges: list[Edge | str] | None = Field(None, title="Edges")
    nodes: list[Node | str] = Field(..., title="Nodes")
    commodities: list[Commodity] | list[str] = Field(..., title="Commodities")
    technologies: list[Technology] | list[str] = Field(..., title="Technologies")
    model_scenarios: list[ModelScenario] | list[str] | None = Field(None, title="Model Scenarios")
    runs: list[Run | str] | None = Field(None, title="Runs")
    urls: list[UrlIndex] | list[str] | None = Field(None, title="Urls")
    featured_scenario: ModelScenario | str | None = Field(None, title="Featured Scenario")
    node_summary: NodeSummary | None = None
    stars: int | None = Field(0, title="Stars")
    views: int | None = Field(0, title="Views")


class ModelPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    models: list[Model] | None = Field(..., title="")


class ModelScenario(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    name: str = Field(..., title="Name")
    description: str | None = Field(None, title="Description")
    version: str | None = Field(None, title="Version")
    status: str | None = Field("draft", title="Status")
    featured: bool | None = Field(False, title="Featured")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str = Field(..., title="Owner")
    model: Model | str = Field(..., title="Model")
    scenario_index_id: UUID = Field(..., title="Scenario Index Id")
    scenario_heritage: ScenarioIndex | str | None = Field(None, title="Scenario Heritage")
    runs: list[Run] | list[str] | None = Field(None, title="Runs")
    featured_run: Run | str | None = Field(None, title="Featured Run")
    urls: list[UrlIndex] | list[str] | None = Field(None, title="Urls")


class ModelScenarioPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    model_scenarios: list[ModelScenario] | None = Field(..., title="")


class Node(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    node_type_alias: str | None = Field(None, title="Node Type Alias")
    properties: dict[str, Any] | None = Field(None, title="Properties")
    is_asset: bool | None = Field(False, title="Is Asset")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str = Field(..., title="Owner")
    node_type: NodeTypeRank | str = Field(..., title="Node Type")
    asset_properties: Asset | str | None = Field(None, title="Asset Properties")
    aliases: list[NodeAlias] | list[str] | None = Field(None, title="Aliases")
    records: list[Record] | list[str] | None = Field(None, title="Records")
    neighbours_out: list[Node] | list[str] | None = Field(None, title="Neighbours Out")
    neighbours_in: list[Node] | list[str] | None = Field(None, title="Neighbours In")
    parents: list[Node] | list[str] | None = Field(None, title="Parents")
    children: list[Node] | list[str] | None = Field(None, title="Children")
    sources: list[Source] | list[str] | None = Field(None, title="Sources")


class NodeAlias(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    alias_type: str = Field(..., title="Alias Type")
    alias_lang: str | None = Field(None, title="Alias Lang")
    primary: bool | None = Field(None, title="Primary")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str = Field(..., title="Owner")
    node: Node | str = Field(..., title="Node")
    power_unit: NodeAlias | str | None = Field(None, title="Power Unit")


class NodeAliasPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    node_aliases: list[NodeAlias] | None = Field(..., title="")


class NodePagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    nodes: list[Node] | None = Field(..., title="")


class NodeSummary(PydanticBaseModel):
    representative_nodes: list[Node] = Field(..., title="Representative Nodes")
    node_counts: dict[str, int] = Field(..., title="Node Counts")


class NodeTypeRank(PydanticBaseModel):
    nodes: list[Node] | list[str] | None = Field(None, title="Nodes")
    discriminator: NodeType
    rank: int = Field(..., title="Rank")


class OperatingMode(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    name: str = Field(..., title="Name")
    properties: dict[str, Any] | None = Field(None, title="Properties")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str = Field(..., title="Owner")
    technology: str | Technology | None = Field(None, title="Technology")


class OperatingModePagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    operating_modes: list[OperatingMode] | None = Field(..., title="")


class ParameterGetResponseSchema(PydanticBaseModel):
    parameters: list[Record] = Field(..., title="Parameters")


class PowerUnit(PydanticBaseModel):
    asset_id: UUID = Field(..., title="Asset Id")
    capacity_rating: str | None = Field(None, title="Capacity Rating")
    is_captive: bool | None = Field(None, title="Is Captive")
    captive_use: str | None = Field(None, title="Captive Use")
    captive_sector: str | None = Field(None, title="Captive Sector")
    has_ccs: bool | None = Field(None, title="Has Ccs")
    river: str | None = Field(None, title="River")
    binational: bool | None = Field(None, title="Binational")
    coal_source: str | None = Field(None, title="Coal Source")
    primary_fuel: str | Commodity | None = Field(None, title="Primary Fuel")
    secondary_fuel: str | Commodity | None = Field(None, title="Secondary Fuel")
    tertiary_fuel: str | Commodity | None = Field(None, title="Tertiary Fuel")
    quaternary_fuel: str | Commodity | None = Field(None, title="Quaternary Fuel")
    quinary_fuel: str | Commodity | None = Field(None, title="Quinary Fuel")


class Publisher(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    name: str = Field(..., title="Name")
    organisation_type: str = Field(..., title="Organisation Type")
    short_name: str | None = Field(None, title="Short Name")
    url: str | None = Field(None, title="Url")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str = Field(..., title="Owner")
    sources: list[Source] | list[str] | None = Field(None, title="Sources")


class PublisherPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    publishers: list[Publisher] | None = Field(..., title="")


class Record(PydanticBaseModel):
    uuid: UUID | None = Field(None, title="Uuid")
    slug: str | None = Field(None, title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime | None = Field(None, title="Creation Time")
    year: int = Field(..., title="Year")
    timestamp: AwareDatetime | None = Field(None, title="Timestamp")
    value: float = Field(..., title="Value")
    properties: dict[str, Any] | None = Field(None, title="Properties")
    owner: str = Field(..., title="Owner")
    source_scenario: SourceScenario | str | None = Field(None, title="Source Scenario")
    model_scenario: ModelScenario | str | None = Field(None, title="Model Scenario")
    year_part: YearPart | str = Field(..., title="Year Part")
    day_part: DayPart | str = Field(..., title="Day Part")
    node: Node | str | None = Field(None, title="Node")
    edge: Edge | str | None = Field(None, title="Edge")
    technology: Technology | str = Field(..., title="Technology")
    commodity: Commodity | str = Field(..., title="Commodity")
    operating_mode: OperatingMode | str = Field(..., title="Operating Mode")
    record_type: RecordType | str = Field(..., title="Record Type")


class RecordPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    records: list[Record] | None = Field(..., title="")


class Run(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    name: str = Field(..., title="Name")
    run_spec: dict[str, Any] | None = Field(..., title="Run Spec")
    validated: bool | None = Field(False, title="Validated")
    description: str | None = Field(None, title="Description")
    featured: bool | None = Field(False, title="Featured")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str = Field(..., title="Owner")
    model: str | Model = Field(..., title="Model")
    model_scenario: str | ModelScenario = Field(..., title="Model Scenario")
    jobs: list[Job] | list[str] | None = Field(None, title="Jobs")
    urls: list[UrlIndex] | list[str] | None = Field(None, title="Urls")


class RunPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    runs: list[Run] | None = Field(..., title="")


class RunResultsChart(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    chart_type: str = Field(..., title="Chart Type")
    series_name: str | None = Field(None, title="Series Name")
    series_properties: dict[str, Any] | None = Field(..., title="Series Properties")
    year: int | None = Field(None, title="Year")
    x: list[float] = Field(..., title="X")
    y: list[float] = Field(..., title="Y")
    node: Node | str | None = Field(None, title="Node")
    edge: Edge | str | None = Field(None, title="Edge")
    technology: str | Technology | None = Field(None, title="Technology")
    commodity: Commodity | str | None = Field(None, title="Commodity")
    year_part: YearPartResource | str | None = Field(None, title="Year Part")


class RunResultsChartPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    run_results_charts: list[RunResultsChart] | None = Field(..., title="")


class Source(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    name: str = Field(..., title="Name")
    short_name: str | None = Field(None, title="Short Name")
    description: str | None = Field(None, title="Description")
    year: int | None = Field(None, title="Year")
    month: int | None = Field(None, title="Month")
    day: int | None = Field(None, title="Day")
    quarter: int | None = Field(None, title="Quarter")
    url: str | None = Field(None, title="Url")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str = Field(..., title="Owner")
    publisher: Publisher | str = Field(..., title="Publisher")
    license: License | str | None = Field(None, title="License")


class SourcePagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    sources: list[Source] | None = Field(..., title="")


class SourceScenario(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    name: str = Field(..., title="Name")
    description: str | None = Field(None, title="Description")
    version: str | None = Field(None, title="Version")
    status: str | None = Field("draft", title="Status")
    featured: bool | None = Field(False, title="Featured")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str = Field(..., title="Owner")
    scenario_index_id: UUID = Field(..., title="Scenario Index Id")
    publisher: Publisher | str = Field(..., title="Publisher")
    source: Source | str = Field(..., title="Source")


class SourceScenarioPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    source_scenarios: list[SourceScenario] | None = Field(..., title="")


class Technology(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    name: str = Field(..., title="Name")
    rank: int | None = Field(None, title="Rank")
    is_storage: bool | None = Field(False, title="Is Storage")
    properties: dict[str, Any] | None = Field(None, title="Properties")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str = Field(..., title="Owner")
    commodities: list[Commodity] | list[str] | None = Field(None, title="Commodities")
    operating_modes: list[OperatingMode] | list[str] | None = Field(None, title="Operating Modes")
    parents: list[Technology] | list[str] | None = Field(None, title="Parents")
    children: list[Technology] | list[str] | None = Field(None, title="Children")


class TechnologyPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    technologies: list[Technology] | None = Field(..., title="")


class UrlIndex(PydanticBaseModel):
    uuid: UUID = Field(..., title="Uuid")
    slug: str = Field(..., title="Slug")
    public: bool | None = Field(True, title="Public")
    creation_time: AwareDatetime = Field(..., title="Creation Time")
    url: str = Field(..., title="Url")
    url_type: URLType
    properties: dict[str, Any] | None = Field(None, title="Properties")
    fullslug: str | None = Field(..., title="Fullslug")
    owner: str = Field(..., title="Owner")
    model: Model | str | None = Field(None, title="Model")
    modelscenario: ModelScenario | str | None = Field(None, title="Modelscenario")
    run: Run | str | None = Field(None, title="Run")


class UrlIndexPagination(PydanticBaseModel):
    current_page: int | None = Field(0, title="current_page")
    next_page: int | None = Field(..., title="next_page")
    total_results: int | None = Field(..., title="total_results")
    url_index: list[UrlIndex] | None = Field(..., title="")


DayPart.model_rebuild()
User.model_rebuild()
YearPart.model_rebuild()
Asset.model_rebuild()
Commodity.model_rebuild()
Edge.model_rebuild()
Job.model_rebuild()
License.model_rebuild()
Model.model_rebuild()
ModelScenario.model_rebuild()
Node.model_rebuild()
OperatingMode.model_rebuild()
ParameterGetResponseSchema.model_rebuild()
Publisher.model_rebuild()
Record.model_rebuild()
Run.model_rebuild()
RunResultsChart.model_rebuild()
